spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          # keycloak issuer-uri of "myrealm" realm
          issuer-uri: http://${KEYCLOAK_HOST:localhost}:${KEYCLOAK_PORT:8181}/auth/realms/${KEYCLOAK_REALM:myrealm}
      client:
        provider:
          keycloak:
            token-uri: http://${KEYCLOAK_HOST:localhost}:${KEYCLOAK_PORT:8181}/auth/realms/${KEYCLOAK_REALM:myrealm}/protocol/openid-connect/token
        registration:
          # client credentials
          keycloak:
            client-id: ${CLIENT_ID:frontendclient}
            client-secret: ${CLIENT_SECRET:VBUWfVtakUlgzjPZwoM3TfrwxL5lo4o9}
            authorization-grant-type: client_credentials
            scope: openid
logging:
  level:
    org:
      springframework:
        security: DEBUG